version: '3.5'
services:
  php:
    image: vergissberlin/boxshot-service
    build: ./images/php/
    command:
      - '/usr/local/bin/php boxshot.php'
    user: '1000:1000'
    volumes:
      - ./app:/app
      - ./data:/data

  php-dev:
    image: vergissberlin/boxshot-service:dev
    build: ./images/php-dev/
    depends_on:
      - php
    command: 'composer install'
    environment:
      - COMPOSER_AUTH
    volumes:
      - ./app:/app
      - ~/.composer:/root/.composer
