version: '3.5'
services:
  php:
    image: vergissberlin/boxshot-service-php
    build: ./images/php/
    command:
      - '/usr/local/bin/php boxshot.php'
    volumes:
      - ./app:/app

  php-dev:
    image: vergissberlin/boxshot-service-php:dev
    build: ./images/php-dev/
    depends_on:
      - php
    command: 'composer install'
    volumes:
      - ./app:/app
